= Getting Started Building Docker Images with Gradle

This repository provides an example application to create, build and start a simple Docker image using the https://github.com/bmuschko/gradle-docker-plugin[Gradle Docker Plugin]. It complements the Gradle Guide, `Getting Started Building Docker Images with Gradle`.

== Build and Execute the Application

To build and execute the application, simply clone this repository to your local machine using the following `git` command:

`git clone https://github.com/mpredli01/getting-started-building-docker-images-with-gradle.git`

Then, follow the Gradle Guide included in this repository that may be found https://github.com/mpredli01/getting-started-building-docker-images-with-gradle/blob/master/src/docs/asciidoc/guide/guide.html[here].

== Want to Contribute?

Are you interested in contributing to this project?  If so, that would be awesome! Just follow these step-by-step instructions:

=== Fork This Repository

* From your own GitHub account, visit this repository.
* Click the fork button.

=== Clone Your Copy of the Repository
* Clone your copy of the repository to your local machine

`git clone https://github.com/{ your GitHub account }/getting-started-building-docker-images-with-gradle.git`

=== Create a Branch
* To make changes, create a branch on your local machine:

* `git checkout -b { branch-name }`
** the `-b` option creates the branch
