== Build and Execute the Application

Applications built with Gradle are launched using the `gradle` command along with built-in and user-defined tasks.

While you won't be executing the `public static void main(String[] args)` method defined in the `App.java` for this example application, you can see how this gets executed by issuing the following command:

`$ gradle clean run --warning-mode all`

The `warning-mode` flag is used for listing any deprecated Gradle features that may be incompatible with the upcoming release of Gradle 8.0.

The output will look like:

[source, gradle]
----
> Task :run
Getting Started Building Docker Images with Gradle

BUILD SUCCESSFUL in 1s
4 actionable tasks: 3 executed, 1 from cache
----

This example application was designed to initiate the `startMyAppContainer` task and allowing the dependency tasks to be executed first, but let's individually execute these tasks.

`$gradle clean createMyAppDockerfile`

The only output is verification that the task successfully completed:

[source, gradle]
----

BUILD SUCCESSFUL in 540ms
2 actionable tasks: 1 executed, 1 from cache
----

However, a `Dockerfile` was generated using the `Dockerfile.tmpl` template file that is stored in the `/build/docker` folder. Let's take a look:

[source, gradle]
----
FROM openjdk:11.0.15-jre-slim
LABEL maintainer="Michael Redlich"
WORKDIR /app2
ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app2/resources:/muDockerApp/classes:/app2/libs/*", "org.gradle.MainApp"]
EXPOSE 9090 5701
RUN ls -la
ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
# template for generated Dockerfile
----

Notice how the Docker commands were prepended on top of the original comment, `# template for generated Dockerfile`.

Now you can execute the `buildMyAppImage` task:

[source, gradle]
----
$gradle clean buildMyAppImage
----

Keep in mind that this task depends on the `createMyAppDockerfile` that you just executed, so the `Dockerfile` will once-again be generated.

The output will look like:

[source, gradle]
----
----

Now, let's execute the `createMyAppContainer` task:

[source, gradle]
----
$ gradle clean createMyAppContainer
----

Again, keep in mind that this task depends on the `buildMyAppImage` task.

The output will look like:

[source, gradle]
----
----


Let's create and build the image and start the container. The `startMyAppContainer` task depends on the tasks that require execution. Therefore, execute:

[source, gradle]
----
$ gradle clean startMyAppContainer
----


[source, gradle]
----
> Task :buildMyAppImage
Building image using context '/usr/local/apps/gradle-apps/getting-started-building-docker-images-with-gradle/build/docker'.
Using images 'test/app2:latest'.
Step 1/7 : FROM openjdk:11.0.15-jre-slim
 ---> 699c24828c34
Step 2/7 : LABEL maintainer="Michael Redlich"
 ---> Using cache
 ---> c7f43ff98289
Step 3/7 : WORKDIR /app2
 ---> Using cache
 ---> 7eb1b1aaa358
Step 4/7 : ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app2/resources:/muDockerApp/classes:/app2/libs/*", "org.gradle.MainApp"]
 ---> Using cache
 ---> 7a6087ee375c
Step 5/7 : EXPOSE 9090 5701
 ---> Using cache
 ---> c2752b3bb2be
Step 6/7 : RUN ls -la
 ---> Using cache
 ---> 8b5c28802e00
Step 7/7 : ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
 ---> Using cache
 ---> c2f34a8c1df6
Successfully built c2f34a8c1df6
Successfully tagged test/app2:latest
Created image with ID 'c2f34a8c1df6'.

> Task :createMyAppContainer
Created container with ID 'b7fb995f1d59698a927333471b446f051ee803ac5a3c174395645bbfbc3b58e8'.

> Task :startMyAppContainer
Starting container with ID 'b7fb995f1d59698a927333471b446f051ee803ac5a3c174395645bbfbc3b58e8'.

BUILD SUCCESSFUL in 4s
5 actionable tasks: 4 executed, 1 from cache
----



=== Docker Version

[source, gradle]
----
`$ gradle getMyDockerVersion`
----

[source, gradle]
----
> Task :getMyDockerVersion
Retrieving Docker version.
Version          : 20.10.21
Git Commit       : 3056208
Go Version       : go1.18.7
Kernel Version   : 5.15.49-linuxkit
Architecture     : amd64
Operating System : linux

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

=== List of Docker Images

[source, gradle]
----
$ gradle getMyDockerImageList
----

[source, gradle]
----
> Task :getMyDockerImageList
Repository Tags : test/app2:latest
Image ID        : sha256:c2f34a8c1df67b413537f9d706c85724bec78cfcaa85374194b10fda76e2fbae
Created         : Sun Jan 08 10:41:03 EST 2023
Virtual Size    : 227459049
-----------------------------------------------
Repository Tags : test/app:latest
Image ID        : sha256:13e86aa2705c759b869ecc3c4de2e3d3a0c44cd13e7d1fa573693e34ebcbefdf
Created         : Sun Jan 08 09:25:07 EST 2023
Virtual Size    : 227459049
-----------------------------------------------
Repository Tags : test/myapp:latest
Image ID        : sha256:ec013200a08d606abdf922e4941d5d557ed7a1718ad0a7f83a32e236503a70f4
Created         : Sat Jan 07 20:14:53 EST 2023
Virtual Size    : 425724205
-----------------------------------------------
Repository Tags : mongo:latest
Image ID        : sha256:0850fead9327a6d88722c27116309022d78e9daf526b407a88de09762c32e620
Created         : Thu Dec 08 21:37:35 EST 2022
Virtual Size    : 699901543
-----------------------------------------------
Repository Tags : cassandra:latest
Image ID        : sha256:5b647422e184fb0fd8f6d5513541e85c06876bdaa68decc026abcb65c3fe4ec5
Created         : Fri Nov 04 19:47:02 EDT 2022
Virtual Size    : 353334938
-----------------------------------------------
Repository Tags : arangodb/arangodb:latest
Image ID        : sha256:d81cf81aaa4b1b637874eab9b877e34dcdee97a00800aaece837fd3d32f7eb56
Created         : Thu Sep 29 10:22:06 EDT 2022
Virtual Size    : 439791606
-----------------------------------------------
Repository Tags : jakartaee-cafe:v1
Image ID        : sha256:f03eac10057c875306561572ce9ce338aa14f4d73917689ec911e891d0a9ce4d
Created         : Tue Sep 13 13:38:25 EDT 2022
Virtual Size    : 484008628
-----------------------------------------------
Repository Tags : openjdk:11.0.15-jre-slim
Image ID        : sha256:699c24828c341c27d15a4f62b5c8fa3c5c986bf52fa76228906c50634f430311
Created         : Mon Jul 11 22:00:45 EDT 2022
Virtual Size    : 227459049
-----------------------------------------------

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
include::plugins.adoc[]
