== Build and Execute the Application

You can launch parts of the application with the `gradle` command and the various tasks.

Since we have a defined `application` block, we can execute the `main()` method defined in the MainApp:

`gradle clean run`

Let's create and build the image and start the container. The `startMyAppContainer` task depends on the tasks that require execution. Therefore, execute:

`gradle clean startMyAppContainer`

`gradle clean startMyAppContainer --warning-mode all`

The `--warning-mode` flag is used for listing deprecated Gradle features that may be incompatible with Gradle 8.0 scheduled for release on { date }.

The generated `Dockerfile` may be found in the `/build/docker` directory.  It contains:

The `Docker.tmpl` file is a template that is used for the plugin to create the official `Dockerfile` in the `build` directory upon success of the build.

`# template for generated Dockerfile'


[source, gradle]
----
> Task :buildMyAppImage
Building image using context '/usr/local/apps/gradle-apps/getting-started-building-docker-images-with-gradle/build/docker'.
Using images 'test/app2:latest'.
Step 1/7 : FROM openjdk:11.0.15-jre-slim
 ---> 699c24828c34
Step 2/7 : LABEL maintainer="Michael Redlich"
 ---> Using cache
 ---> c7f43ff98289
Step 3/7 : WORKDIR /app2
 ---> Using cache
 ---> 7eb1b1aaa358
Step 4/7 : ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app2/resources:/muDockerApp/classes:/app2/libs/*", "org.gradle.MainApp"]
 ---> Using cache
 ---> 7a6087ee375c
Step 5/7 : EXPOSE 9090 5701
 ---> Using cache
 ---> c2752b3bb2be
Step 6/7 : RUN ls -la
 ---> Using cache
 ---> 8b5c28802e00
Step 7/7 : ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
 ---> Using cache
 ---> c2f34a8c1df6
Successfully built c2f34a8c1df6
Successfully tagged test/app2:latest
Created image with ID 'c2f34a8c1df6'.

> Task :createMyAppContainer
Created container with ID 'b7fb995f1d59698a927333471b446f051ee803ac5a3c174395645bbfbc3b58e8'.

> Task :startMyAppContainer
Starting container with ID 'b7fb995f1d59698a927333471b446f051ee803ac5a3c174395645bbfbc3b58e8'.

BUILD SUCCESSFUL in 4s
5 actionable tasks: 4 executed, 1 from cache
----

=== Docker Version

You can 
`gradle getMyDockerVersion`

[source, gradle]
----
> Task :getMyDockerVersion
Retrieving Docker version.
Version          : 20.10.21
Git Commit       : 3056208
Go Version       : go1.18.7
Kernel Version   : 5.15.49-linuxkit
Architecture     : amd64
Operating System : linux

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

=== List of Docker Images

`gradle getMyDockerImageList`

[source, gradle]
----
> Task :getMyDockerImageList
Repository Tags : test/app2:latest
Image ID        : sha256:c2f34a8c1df67b413537f9d706c85724bec78cfcaa85374194b10fda76e2fbae
Created         : Sun Jan 08 10:41:03 EST 2023
Virtual Size    : 227459049
-----------------------------------------------
Repository Tags : test/app:latest
Image ID        : sha256:13e86aa2705c759b869ecc3c4de2e3d3a0c44cd13e7d1fa573693e34ebcbefdf
Created         : Sun Jan 08 09:25:07 EST 2023
Virtual Size    : 227459049
-----------------------------------------------
Repository Tags : test/myapp:latest
Image ID        : sha256:ec013200a08d606abdf922e4941d5d557ed7a1718ad0a7f83a32e236503a70f4
Created         : Sat Jan 07 20:14:53 EST 2023
Virtual Size    : 425724205
-----------------------------------------------
Repository Tags : mongo:latest
Image ID        : sha256:0850fead9327a6d88722c27116309022d78e9daf526b407a88de09762c32e620
Created         : Thu Dec 08 21:37:35 EST 2022
Virtual Size    : 699901543
-----------------------------------------------
Repository Tags : cassandra:latest
Image ID        : sha256:5b647422e184fb0fd8f6d5513541e85c06876bdaa68decc026abcb65c3fe4ec5
Created         : Fri Nov 04 19:47:02 EDT 2022
Virtual Size    : 353334938
-----------------------------------------------
Repository Tags : arangodb/arangodb:latest
Image ID        : sha256:d81cf81aaa4b1b637874eab9b877e34dcdee97a00800aaece837fd3d32f7eb56
Created         : Thu Sep 29 10:22:06 EDT 2022
Virtual Size    : 439791606
-----------------------------------------------
Repository Tags : jakartaee-cafe:v1
Image ID        : sha256:f03eac10057c875306561572ce9ce338aa14f4d73917689ec911e891d0a9ce4d
Created         : Tue Sep 13 13:38:25 EDT 2022
Virtual Size    : 484008628
-----------------------------------------------
Repository Tags : openjdk:11.0.15-jre-slim
Image ID        : sha256:699c24828c341c27d15a4f62b5c8fa3c5c986bf52fa76228906c50634f430311
Created         : Mon Jul 11 22:00:45 EDT 2022
Virtual Size    : 227459049
-----------------------------------------------

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
include::plugins.adoc[]
