== Build and Execute the Application

Applications built with Gradle are launched using the `gradle` command along with built-in and user-defined tasks.

=== Execute Java Applications

While you won't be required to execute the `public static void main(String[] args)` method defined in the `App.java` file for this example application, you can see at least how this gets executed by issuing the following command:

[source, gradle]
----
$ gradle run --warning-mode all
----

The `warning-mode` flag is used for listing any deprecated Gradle features that may be incompatible with the upcoming release of Gradle 8.0.

The output will look like:

[source, gradle]
----
> Task :run
Getting Started Building Docker Images with Gradle

BUILD SUCCESSFUL in 1s
4 actionable tasks: 3 executed, 1 from cache
----

This displays the string, "Getting Started Building Docker Images with Gradle," defined in the `getGreeting()` method in `App.java` that generated using the `gradle init` command.

=== Execute Tasks

This example application was designed to initiate the `startMyAppContainer` task and allow the dependency tasks to be executed first, but let's individually execute those task dependencies.

==== `createMyAppDockerfile`

[source, gradle]
----
$ gradle createMyAppDockerfile
----

The only output is verification that the task successfully completed:

[source, gradle]
----
BUILD SUCCESSFUL in 540ms
2 actionable tasks: 1 executed, 1 from cache
----

However, a `Dockerfile` was quietly generated based on the `Dockerfile.tmpl` template. You can find the generated `Dockerfile` file in the `/build/docker` folder.

Let's take a look:

[source, gradle]
----
FROM openjdk:11.0.15-jre-slim
LABEL maintainer="Michael Redlich"
WORKDIR /app2
ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app2/resources:/muDockerApp/classes:/app2/libs/*", "org.gradle.MainApp"]
EXPOSE 9090 5701
RUN ls -la
ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
# template for generated Dockerfile
----

Notice how the Docker commands were prepended on top of the original comment, `# template for generated Dockerfile`.

==== `buildMyAppImage`

Now you can execute the `buildMyAppImage` task:

[source, gradle]
----
$ gradle buildMyAppImage
----

Keep in mind that this task depends on the `createMyAppDockerfile` that you just executed, so the `Dockerfile` will once-again be generated.

Let's review the output:

[source, gradle]
----
> Task :buildMyAppImage
Building image using context '/usr/local/apps/gradle-apps/getting-started-building-docker-images-with-gradle/build/docker'.
Using images 'test/app2:latest'.
Step 1/7 : FROM openjdk:11.0.15-jre-slim
 ---> 699c24828c34
Step 2/7 : LABEL maintainer="Michael Redlich"
 ---> Using cache
 ---> c7f43ff98289
Step 3/7 : WORKDIR /app2
 ---> Using cache
 ---> 7eb1b1aaa358
Step 4/7 : ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app2/resources:/muDockerApp/classes:/app2/libs/*", "org.gradle.MainApp"]
 ---> Using cache
 ---> 7a6087ee375c
Step 5/7 : EXPOSE 9090 5701
 ---> Using cache
 ---> c2752b3bb2be
Step 6/7 : RUN ls -la
 ---> Using cache
 ---> 8b5c28802e00
Step 7/7 : ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
 ---> Using cache
 ---> c2f34a8c1df6
Successfully built c2f34a8c1df6
Successfully tagged test/app2:latest
Created image with ID 'c2f34a8c1df6'.

BUILD SUCCESSFUL in 1s
3 actionable tasks: 2 executed, 1 from cache
----

You can verify creation of the new image by executing the `docker` command:

[source, gradle]
----
$ docker images
----

Let's review the output:

[source, gradle]
----
test/app2                                       latest                c2f34a8c1df6   28 hours ago    227MB
test/app                                        latest                13e86aa2705c   29 hours ago    227MB
test/myapp                                      latest                ec013200a08d   42 hours ago    426MB
mongo                                           latest                0850fead9327   4 weeks ago     700MB
cassandra                                       latest                5b647422e184   2 months ago    353MB
arangodb/arangodb                               latest                d81cf81aaa4b   3 months ago    440MB
jakartaee-cafe                                  v1                    f03eac10057c   3 months ago    484MB
----

==== `createMyAppContainer`

Now, let's execute the `createMyAppContainer` task:

[source, gradle]
----
$ gradle createMyAppContainer
----

Again, keep in mind that this task depends on the `buildMyAppImage` task.

Let's review the output:

[source, gradle]
----
> Task :createMyAppContainer
Created container with ID 'ea83da3cc17681424105d4c3602789b858cb0daee45b40efd2d36bac1b22f59c'.

BUILD SUCCESSFUL in 1s
4 actionable tasks: 3 executed, 1 from cache
----

==== `startMyAppContainer`

Now let's run the entire process by executing the `startMyAppContainer` task that executes all the dependencies:

[source, gradle]
----
$ gradle startMyAppContainer
----

Let's review the output:

[source, gradle]
----
> Task :startMyAppContainer
Starting container with ID '0f150837001528439c9957b7b077b3d85be25fd86b98c3f491044f0a65083e29'.

BUILD SUCCESSFUL in 2s
5 actionable tasks: 4 executed, 1 from cache
----

The next few tasks may be executed independently from the `startMyAppContainer` task.

==== `getMyDockerVersion`

[source, gradle]
----
$ gradle getMyDockerVersion
----

[source, gradle]
----
> Task :getMyDockerVersion
Retrieving Docker version.
Version          : 20.10.21
Git Commit       : 3056208
Go Version       : go1.18.7
Kernel Version   : 5.15.49-linuxkit
Architecture     : amd64
Operating System : linux

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

==== `getMyDockerInfo`

[source, gradle]
----
$ gradle getMyDockerInfo
----

[source, gradle]
----
> Task :getMyDockerInfo
Retrieving Docker info.
Debug                : false
Containers           : 25
Driver               : overlay2
Driver Statuses      : [[Backing Filesystem, extfs], [Supports d_type, true], [Native Overlay Diff, true], [userxattr, false]]
Images               : 53
IPv4 Forwarding      : true
Index Server Address : https://index.docker.io/v1/
Init Path            : null
Init SHA1            : null
Kernel Version       : 5.15.49-linuxkit
Sockets              : null
Memory Limit         : true
nEvent Listener      : 4
NFd                  : 46
NGoroutines          : 49
Swap Limit           : true
Execution Driver     : null

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

==== `getMyDockerImageList`

[source, gradle]
----
$ gradle getMyDockerImageList
----

[source, gradle]
----
> Task :getMyDockerImageList
Repository Tags : test/app2:latest
Image ID        : sha256:c2f34a8c1df67b413537f9d706c85724bec78cfcaa85374194b10fda76e2fbae
Created         : Sun Jan 08 10:41:03 EST 2023
Virtual Size    : 227459049
-----------------------------------------------
Repository Tags : test/app:latest
Image ID        : sha256:13e86aa2705c759b869ecc3c4de2e3d3a0c44cd13e7d1fa573693e34ebcbefdf
Created         : Sun Jan 08 09:25:07 EST 2023
Virtual Size    : 227459049
-----------------------------------------------
Repository Tags : test/myapp:latest
Image ID        : sha256:ec013200a08d606abdf922e4941d5d557ed7a1718ad0a7f83a32e236503a70f4
Created         : Sat Jan 07 20:14:53 EST 2023
Virtual Size    : 425724205
-----------------------------------------------
Repository Tags : mongo:latest
Image ID        : sha256:0850fead9327a6d88722c27116309022d78e9daf526b407a88de09762c32e620
Created         : Thu Dec 08 21:37:35 EST 2022
Virtual Size    : 699901543
-----------------------------------------------
Repository Tags : cassandra:latest
Image ID        : sha256:5b647422e184fb0fd8f6d5513541e85c06876bdaa68decc026abcb65c3fe4ec5
Created         : Fri Nov 04 19:47:02 EDT 2022
Virtual Size    : 353334938
-----------------------------------------------
Repository Tags : arangodb/arangodb:latest
Image ID        : sha256:d81cf81aaa4b1b637874eab9b877e34dcdee97a00800aaece837fd3d32f7eb56
Created         : Thu Sep 29 10:22:06 EDT 2022
Virtual Size    : 439791606
-----------------------------------------------
Repository Tags : jakartaee-cafe:v1
Image ID        : sha256:f03eac10057c875306561572ce9ce338aa14f4d73917689ec911e891d0a9ce4d
Created         : Tue Sep 13 13:38:25 EDT 2022
Virtual Size    : 484008628
-----------------------------------------------
Repository Tags : openjdk:11.0.15-jre-slim
Image ID        : sha256:699c24828c341c27d15a4f62b5c8fa3c5c986bf52fa76228906c50634f430311
Created         : Mon Jul 11 22:00:45 EDT 2022
Virtual Size    : 227459049
-----------------------------------------------

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

include::summary.adoc[]
