== Getting Started

Let's get started on building a Docker image!

=== What You'll Build

You will be using the necessary classes defined in the Gradle Docker Plugin to create a `Dockerfile`, build the image, create the container, then start the container.

=== What You'll Need

* A text editor or IDE such as https://www.jetbrains.com/idea/download/[IntelliJ IDEA]
* A Java Development Kit (JDK), version 11+
* The latest version of https://www.docker.com/[Docker]
* The latest https://gradle.org/install/[Gradle] distribution
* The https://github.com/docker-java/docker-java[Docker Java] library

[IMPORTANT]
This plugin requires Gradle >= 7.4.0.

=== Initiate the Project

Follow the Gradle Guide, https://docs.gradle.org/current/samples/sample_building_java_applications_multi_project.html[Building Java Applications with Libraries Sample] to initiate your project.

=== Java Application Plugin

You will be using the https://bmuschko.github.io/gradle-docker-plugin/current/user-guide/#java-application-plugin[Java Application Plugin] for this example application.

=== Update the `build.gradle` File

Now that you have a directory structure in place, let's build upon the `build.gradle` file that was generated by `gradle init` command.

First, let's import the required classes:

[source, gradle]
----
import com.bmuschko.gradle.docker.tasks.DockerInfo
import com.bmuschko.gradle.docker.tasks.DockerVersion
import com.bmuschko.gradle.docker.tasks.DockerOperation

import com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer
import com.bmuschko.gradle.docker.tasks.container.DockerExecContainer
import com.bmuschko.gradle.docker.tasks.container.DockerStartContainer
import com.bmuschko.gradle.docker.tasks.container.DockerStopContainer

import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.DockerListImages
----

Let's update the `plugins` block with the required plugins:

[source, gradle]
----
plugins {
    id 'java'
    id 'application'
    id 'java-gradle-plugin'
    id 'com.bmuschko.docker-java-application' version '9.1.0'
    id 'com.bmuschko.docker-remote-api' version '9.1.0'
}
----

Let's update our `dependencies` block with the required dependencies:

[source, gradle]
----
dependencies {
implementation group: 'com.bmuschko', name: 'gradle-docker-plugin', version: '6.7.0'
implementation group: 'com.bmuschko', name: 'asciidoctorj-tabbed-code-extension', version: '0.3'
implementation(buildsrclibs.asciidoctor.jvm.plugin)
runtimeOnly(buildsrclibs.asciidoctorj.tabbed.code.extension)
}
----


=== Java Application Plugin Classes

The Java classes are instantiated in the `build.gradle` file, in other words, you won't be using the `new` keyword. Instead,

The `Docker.tmpl` file is a template that is used for the plugin to create the official `Dockerfile` in the `build` directory upon success of the build.

`# template for generated Dockerfile'

`gradle clean startMyAppContainer --warning-mode all`

The `--warning-mode` flag is used for listing deprecated Gradle features that may be incompatible with Gradle 8.0 scheduled for release on { date }.

The generated `Dockerfile` may be found in the `/build/docker` directory.  It contains:

[source, gradle]
----
FROM openjdk:11.0.15-jre-slim
LABEL maintainer="Michael Redlich \"mike@redlich.net\""
WORKDIR /app
COPY libs libs/
COPY classes classes/
ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app/resources:/app/classes:/app/libs/*", "org.gradle.MainApp"]
EXPOSE 9090 5701
RUN ls -la
ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
# template for generated Dockerfile
----


include::tasks.adoc[]
