== Tasks

A Gradle Task represents a single atomic piece of work for a Gradle build, such as compiling classes or generating JavaDocs. Tasks are comprised by series of actions as defined by implementations of the https://docs.gradle.org/7.6/javadoc/org/gradle/api/Action.html[`Action`] interface. Tasks are allowed to depend on other tasks.

You can create your own custom tasks by extending the https://docs.gradle.org/7.6/javadoc/org/gradle/api/DefaultTask.html[`DefaultTask`] class which implements the https://docs.gradle.org/7.6/javadoc/org/gradle/api/Task.html[`Task`] interface.

In the Getting Started section, you imported all the required Gradle Tasks for this example application.

[IMPORTANT]
Directly instantiating these classes is *not* supported. You can only instantiate them in the Gradle API or DSL, such as the `build.gradle` file. Attempting to directly instantiate these classes will result in an exception of type https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskInstantiationException.html[`TaskInstantiationException`].

[source, gradle]
----
FROM openjdk:11.0.15-jre-slim
LABEL maintainer="Michael Redlich \"mike@redlich.net\""
WORKDIR /app
COPY libs libs/
COPY classes classes/
ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app/resources:/app/classes:/app/libs/*", "org.gradle.MainApp"]
EXPOSE 9090 5701
RUN ls -la
ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
# template for generated Dockerfile
----

=== Defined Tasks

Let's review a list of defined task names and their dependencies that you will use for the example application:

* `createMyAppDockerfile` generates a working `Dockerfile` file based on the template, `Dockefile.tmpl`.
* `buildMyAppImage` builds the Docker image from the generated `Dockerfile`.
** depends on `createMyAppDockerfile`
* `createMyAppContainer` creates the Docker container.
** depends on `buildMyAppImage`
* `startMyAppContainer` starts the Docker container.
** depends on `createMyAppContainer`
* `stopMyAppContainer`
* `executeMyAppContainer`
* `getMyDockerInfo`
* `getMyDockerVersion`
* `getMyDockerImageList`

You will be providing the definitions to all of these tasks within your `build.gradle` file as we review each one.

=== Dockerfile Template

As a starting point, you will need a Docker file template for this application. In the root directory of your project, create a file named `Dockerfile.tmpl` and add the following comment:

[source, gradle]
----
# template for generated Dockerfile
----

=== Create Dockerfile

This task instantiates the https://bmuschko.github.io/gradle-docker-plugin/9.1.0/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html[`Dockerfile`] class to generate a standard `Dockerfile` based on a template file, `Dockerfile.tmpl` that you just created. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task createMyAppDockerfile(type: Dockerfile) {
    instruction('FROM openjdk:11.0.15-jre-slim')
    instruction('LABEL maintainer=\"Michael Redlich\"')
    instruction('WORKDIR /app2')
    instruction('ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app2/resources:/muDockerApp/classes:/app2/libs/*", "org.gradle.MainApp"]')
    instruction('EXPOSE 9090 5701')
    instruction('RUN ls -la')
    environmentVariable('JAVA_OPTS', '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap')
    instructionsFromTemplate(file('Dockerfile.tmpl'))
    }
----

There are three methods defined in this task:

* The `instruction()` method specifies Docker commands
* The `environmentalVariable()` method specifies any environmental variables
* The `instructionsFromTemplate()` method specifies the `Dockerfile.tmpl` file as a template

=== Build the Image

The `buildMyAppImage` task instantiates the https://bmuschko.github.io/gradle-docker-plugin/9.1.0/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html[`DockerBuildImage`] class to build the Docker image. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task buildMyAppImage(type: DockerBuildImage) {
    dependsOn(createMyAppDockerfile)
    inputDir.set(file('build/docker'))
    images.add('test/app2:latest')
    }
----

There are three methods define in this task:

* The `dependsOn()` method specifies a task that should be executed before this task
* The `inputDir()` method specifies a location where to place the generated `Dockerfile`
* The `images.add()` method specifies the name of the Docker image

=== Create the Docker Container

The `createMyAppContainer` task instantiates the https://bmuschko.github.io/gradle-docker-plugin/9.1.0/api/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.html[`DockerCreateContainer`] class to create a Docker container. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task createMyAppContainer(type: DockerCreateContainer) {
    dependsOn(buildMyAppImage)
    targetImageId(buildMyAppImage.getImageId())
    }
----

There are two methods defined in this task:

* The `dependsOn()` method specifies a task that should be execute before this task
* The `targetImageId()` method specifies a Docker image ID

=== Start the Docker Container

The `startMyAppContainer` task instantiates the https://bmuschko.github.io/gradle-docker-plugin/9.1.0/api/com/bmuschko/gradle/docker/tasks/container/DockerStartContainer.html[`DockerStartContainer`] class to start a Docker container. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task startMyAppContainer(type: DockerStartContainer) {
    dependsOn(createMyAppContainer)
    targetContainerId(createMyAppContainer.getContainerId())
    }
----

There are two methods defined in this task:

* The `dependsOn()` method specifies a task that should be execute before this task
* The `targetContainerId()` method specifies the Docker image ID to use for starting the container

=== Stop the Docker Container

The `stopMyAppcontainer` task instantiates the https://bmuschko.github.io/gradle-docker-plugin/9.1.0/api/com/bmuschko/gradle/docker/tasks/container/DockerStopContainer.html[`DockerStopContainer`] class to stop a running Docker container. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task stopMyAppContainer(type: DockerStopContainer) {
    targetContainerId(createMyAppContainer.getContainerId())
    }
----

There is only one method defined in this task:

* The `targetContainerId()` method specifies the Docker image ID to use for stopping the running container

=== Execute the Container

The `executeMyAppContainer` task instantiates the https://bmuschko.github.io/gradle-docker-plugin/9.1.0/api/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.html[`DockerExecContainer`] class to execute a Docker container. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task executeMyAppContainer(type: DockerExecContainer) {
    targetContainerId(createMyAppContainer.getContainerId())
    }
----

There is only one method defined in this task:

* The `targetContainerId()` method specifies the Docker image ID to use for executing a Docker container.

=== Obtain the Docker Information

The `getMyDockerInfo` task instantiates the https://bmuschko.github.io/gradle-docker-plugin/9.1.0/api/com/bmuschko/gradle/docker/tasks/DockerInfo.html[`DockerInfo`] class to retrieve your local Docker installation. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task getMyDockerInfo(type: DockerInfo) {
    }
----

There are no defined methods in this task, however, executing this task invokes the `runRemoteCommand()` method defined in the `DockerInfo` class.

=== Obtain the Docker Version

The `getMyDockerVersion` task instantiates the `DockerVersion` class to retrieve the version of your local Docker installation. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task getMyDockerVersion(type: DockerVersion) {
    }
----

There are no defined methods in this task, however, executing this task invokes the `runRemoteCommand()` method defined in the `DockerVersion` class.

=== Obtain the List of Docker Images

The `getMyDockerImageList` task instantiates the There are no defined methods in this task, however, executing this task invokes the `runRemoteCommand()` method defined in the `DockerInfo` class.[`DockerListImages`] class to retrieve a list of your local Docker images. You can add the following content to your `build.gradle` file:

[source, gradle]
----
task getMyDockerImageList(type: DockerListImages) {
    }
----

There are no defined methods in this task, however, executing this task invokes the `runRemoteCommand()` method defined in the `DockerListImages` class.

Now that you have added these tasks to your `build.gradle` file, it's time to exercise the example application!

include::build-and-execute.adoc[]
