== Tasks

A Gradle Task represents a single atomic piece of work for a Gradle build, such as compiling classes or generating JavaDocs. Tasks are comprised by series of actions as defined by implementations of the https://docs.gradle.org/7.6/javadoc/org/gradle/api/Action.html[`Action`] interface. Tasks are allowed to depend on other tasks.

You can create your own custom tasks by extending the https://docs.gradle.org/7.6/javadoc/org/gradle/api/DefaultTask.html[`DefaultTask`] class which implements the https://docs.gradle.org/7.6/javadoc/org/gradle/api/Task.html[`Task`] interface.

In the Getting Started section, you imported all the required classes for this example application

[IMPORTANT]
Directly instantiating these classes is *not* supported. You can only instatiate them in the Gradle API or DSL, such as the `build.gradle` file.

=== Defined Tasks

These are the defined task names for the example application:

* `createMyAppDockerfile` generates a working `Dockerfile` file based on the template, `Dockefile.tmpl`.
* `buildMyAppImage` builds the Docker image from the generated `Dockerfile`.
** depends on `createMyAppDockerfile`
* `createMyAppContainer` creates the Docker container.
** depends on `buildMyAppImage`
* `startMyAppContainer` starts the Docker container.
** depends on `createMyAppContainer`
* `stopMyAppContainer`
* `executeMyAppContainer`
* `getMyDockerInfo`
* `getMyDockerVersion`
* `getMyDockerImageList`
* `getMyDockerOperation`

You can individually add all of these to your `build.gradle` file. We will discuss each of these and their corresponding classes.

=== Create Dockerfile

This task instantiates the `Dockerfile` class to generate a standard `Dockerfile` based on a template file, `Dockerfile.tmpl`. You will need to manually create this file and add the following contents:

[source, gradle]
----
# template for generated Dockerfile
----

This task contains a few calls to the `instruction()` method that specify the various Docker commands. The `environmentalVariable()` method accepts the environmental variable, `JAVA_OPTS` and the two values. The `instructionsFromTemplate()` method specifies the `Dockerfile.tmpl` file.

[source, gradle]
----
task createMyAppDockerfile(type: Dockerfile) {
instruction('FROM openjdk:11.0.15-jre-slim')
instruction('LABEL maintainer=\"Michael Redlich\"')
instruction('WORKDIR /app2')
instruction('ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-cp", "/app2/resources:/muDockerApp/classes:/app2/libs/*", "org.gradle.MainApp"]')
instruction('EXPOSE 9090 5701')
instruction('RUN ls -la')
environmentVariable('JAVA_OPTS', '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap')
instructionsFromTemplate(file('Dockerfile.tmpl'))
}
----

=== Build the Image

The `buildMyAppImage` task instantiates the `DockerBuildImage` class to build the Docker image.

[source, gradle]
----
task buildMyAppImage(type: DockerBuildImage) {
    dependsOn(createMyAppDockerfile)
    inputDir.set(file('build/docker'))
    images.add('test/app2:latest')
    }
----

=== Create the Docker Container

The `createMyAppContainer` task instantiates the `DockerCreateContainer` class.

[source, gradle]
----
task createMyAppContainer(type: DockerCreateContainer) {
    dependsOn(buildMyAppImage)
    targetImageId(buildMyAppImage.getImageId())
    }
----

=== Start the Docker Container

The `startMyAppContainer` task instantiates the `DockerStartContainer` class.

[source, gradle]
----
task startMyAppContainer(type: DockerStartContainer) {
    dependsOn(createMyAppContainer)
    targetContainerId(createMyAppContainer.getContainerId())
    }
----

=== Stop the Docker Container

The `` task instantiates the `` class.

[source, gradle]
----
task stopMyAppContainer(type: DockerStopContainer) {
    targetContainerId(createMyAppContainer.getContainerId())
    }
----

=== Execute the Container

The `executeMyAppContainer` task instantiates the `DockerExecContainer` class.

[source, gradle]
----
task executeMyAppContainer(type: DockerExecContainer) {
    targetContainerId(createMyAppContainer.getContainerId())
    }
----

=== Obtain the Docker Information

The `getMyDockerInfo` task instantiates the `DockerInfo` class.

[source, gradle]
----
task getMyDockerInfo(type: DockerInfo) {
    }
----

=== Obtain the Docker Version

The `getMyDockerVersion` task instantiates the `DockerVersion` class.

[source, gradle]
----
task getMyDockerVersion(type: DockerVersion) {
    }
----

=== Obtain the List of Docker Images

The `getMyDockerImageList` task instantiates the `DockerListImages` class.

[source, gradle]
----
task getMyDockerImageList(type: DockerListImages) {
    }
----

include::build-and-execute.adoc[]
